CC = g++
SERVER_SOURCE_FILE = src/main.cpp
CLIENT_SOURCE_FILE = src/client_main.cpp
COMPILER_FLAGS = 
LINKER_FLAGS = -lSDL3 -lSDL3_image -lSDL3_ttf
SERVER_OUTPUT = build/main_out.exe
CLIENT_OUTPUT = build/client_main.exe


client : CREATE_CLIENT_OUT	
	./${CLIENT_OUTPUT}


server : CREATE_SERVER_OUT
	./${SERVER_OUTPUT}

CLEAR :
	TERM=xterm clear

CREATE_SERVER_OUT: ${SERVER_SOURCE_FILE}
	${CC} ${SERVER_SOURCE_FILE} ${COMPILER_FLAGS} ${LINKER_FLAGS} -o ${SERVER_OUTPUT}

CREATE_CLIENT_OUT : ${CLIENT_SOURCE_FILE} 
	${CC} ${CLIENT_SOURCE_FILE} ${COMPILER_FLAGS} ${LINKER_FLAGS} -o ${CLIENT_OUTPUT}
